# Generated by Django 4.1.2 on 2022-11-21 12:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('statuses', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='status',
            old_name='date_joined',
            new_name='created_at',
        ),
    ]
