# Generated by Django 4.1.2 on 2022-11-16 12:44

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='author',
        ),
        migrations.AddField(
            model_name='task',
            name='executor',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
    ]
