# Generated by Django 4.1.2 on 2022-12-20 14:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='labelfortask',
            old_name='label',
            new_name='labels',
        ),
    ]
