# Generated by Django 4.1.2 on 2022-11-21 13:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0005_labelfortask_alter_task_labels'),
    ]

    operations = [
        migrations.RenameField(
            model_name='labelfortask',
            old_name='label',
            new_name='labels',
        ),
    ]
